# Generated by Django 5.2.2 on 2025-06-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
