# Generated by Django 5.2.2 on 2025-06-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_module_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
